#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : scikit-image
Version  : 0.15.0
Release  : 47
URL      : https://files.pythonhosted.org/packages/e0/46/ca035f5d7d3414124a3a5ef22cd2e75c0c5149042a668375f1d44eb69f8f/scikit-image-0.15.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/e0/46/ca035f5d7d3414124a3a5ef22cd2e75c0c5149042a668375f1d44eb69f8f/scikit-image-0.15.0.tar.gz
Summary  : Image processing routines for SciPy
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: scikit-image-bin = %{version}-%{release}
Requires: scikit-image-license = %{version}-%{release}
Requires: scikit-image-python = %{version}-%{release}
Requires: scikit-image-python3 = %{version}-%{release}
Requires: Pillow
Requires: PyWavelets
Requires: cloudpickle
Requires: dask
Requires: imageio
Requires: matplotlib
Requires: networkx
Requires: scipy
BuildRequires : Cython
BuildRequires : Pillow
BuildRequires : PyWavelets
BuildRequires : buildreq-distutils3
BuildRequires : cloudpickle
BuildRequires : dask
BuildRequires : imageio
BuildRequires : matplotlib
BuildRequires : networkx
BuildRequires : numpy
BuildRequires : python3-dev
BuildRequires : scikit-learn
BuildRequires : scipy

%description
Image processing algorithms for SciPy, including IO, morphology, filtering,
        warping, color manipulation, object detection, etc.
        
        Please refer to the online documentation at

%package bin
Summary: bin components for the scikit-image package.
Group: Binaries
Requires: scikit-image-license = %{version}-%{release}

%description bin
bin components for the scikit-image package.


%package license
Summary: license components for the scikit-image package.
Group: Default

%description license
license components for the scikit-image package.


%package python
Summary: python components for the scikit-image package.
Group: Default
Requires: scikit-image-python3 = %{version}-%{release}

%description python
python components for the scikit-image package.


%package python3
Summary: python3 components for the scikit-image package.
Group: Default
Requires: python3-core
Provides: pypi(scikit_image)
Requires: pypi(imageio)
Requires: pypi(matplotlib)
Requires: pypi(networkx)
Requires: pypi(pillow)
Requires: pypi(pywavelets)
Requires: pypi(scipy)

%description python3
python3 components for the scikit-image package.


%prep
%setup -q -n scikit-image-0.15.0
cd %{_builddir}/scikit-image-0.15.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583784818
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -fno-lto -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/scikit-image
cp %{_builddir}/scikit-image-0.15.0/LICENSE.txt %{buildroot}/usr/share/package-licenses/scikit-image/5bf5af38f581ac8143562a9ea27083cf358fa476
cp %{_builddir}/scikit-image-0.15.0/doc/tools/LICENSE.txt %{buildroot}/usr/share/package-licenses/scikit-image/fb50fd87a0153fd93be5975f012fa41347306040
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/skivi

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/scikit-image/5bf5af38f581ac8143562a9ea27083cf358fa476
/usr/share/package-licenses/scikit-image/fb50fd87a0153fd93be5975f012fa41347306040

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
